import type { IncidentDraft } from './types';
export const DRAFT_STORAGE_KEY = 'cfr-financial-fraud-draft-v1';

export const emptyDraft: IncidentDraft = {
  step: 0,
  immediateActions: {},
  narrative: '',
  interpretation: null,
  interpretationConfirmed: false,
  sourceMap: {},
  timeline: [],
  transactions: [],
  amount: '',
  date: '',
  time: '',
  paymentMethod: '',
  provider: '',
  transactionId: '',
  recipient: '',
  multipleTransactions: 'no',
  contactChannel: '',
  contactChannels: [],
  suspectPhone: '',
  suspectHandle: '',
  suspectWebsite: '',
  suspectDisplayName: '',
  suspectOrgClaimed: '',
  contactIdentifiers: [],
  evidence: [],
  reporterRelation: 'self',
  fullName: '',
  mobile: '',
  victimName: '',
  victimMobile: '',
  primaryContactRole: 'reporter',
  orgName: '',
  orgType: 'Private Company',
  orgRegId: '',
  reporterDesignation: '',
  language: 'English',
  state: '',
  city: '',
  email: '',
  incidentLocationDiffers: false,
  incidentState: '',
  incidentCity: '',
  isSafeToCall: true,
  safeContactMethod: 'Mobile call',
  safeTimeWindow: 'Anytime',
  alternativeContact: '',
  reviewed: false,
  prototypeConsent: false,
  savedAt: null,
};

export const scamCards = [
  ['Fake investment and trading schemes', 'Promises of guaranteed returns, urgent deposits or private trading groups are common warning signs.'],
  ['Digital-arrest impersonation scams', 'Police and regulators do not demand secret payments to avoid a supposed digital arrest.'],
  ['Fake job or task scams', 'Be cautious when a job requires deposits, paid tasks or transfers to unlock earnings.'],
] as const;
